#!/usr/bin/python3
# list which xpra package builds are missing for a given release,
# by checking the local mirror of the build output repos.
#
# usage: list-missing <beta|stable|lts> <version>
# eg:    list-missing lts 5.1.6

import glob
import os
import sys

REPOS_ROOT = os.path.expanduser("~/projects/repos")

# kept in sync with repos/bin/update-rpm-repos.sh and repos/bin/update-deb-packages.py
RPM_DISTROS = ["Fedora", "CentOS", "almalinux", "rockylinux", "oraclelinux"]
RPM_ARCHES = ["x86_64", "aarch64", "riscv64"]

DEBIAN_DISTROS = "bullseye,bookworm,trixie,forky,sid".split(",")
UBUNTU_DISTROS = "bionic,focal,jammy,noble,resolute".split(",")
DEB_ARCHES = ["amd64", "arm64", "riscv64"]

MACOS_ARCHES = ["x86_64", "arm64"]
MSWINDOWS_ARCHES = ["x86_64", "aarch64"]


def rpm_missing(channel, version):
    missing = []
    for distro in RPM_DISTROS:
        distro_dir = os.path.join(REPOS_ROOT, channel, distro)
        if not os.path.isdir(distro_dir):
            continue
        for release in sorted(os.listdir(distro_dir)):
            release_path = os.path.join(distro_dir, release)
            # skip the "8" -> "8.10" style latest-point-release symlinks,
            # the real versioned directory is checked directly
            if os.path.islink(release_path) or not os.path.isdir(release_path):
                continue
            for arch in RPM_ARCHES:
                arch_dir = os.path.join(release_path, arch)
                if not os.path.isdir(arch_dir):
                    continue
                pattern = os.path.join(arch_dir, "xpra-%s-*.%s.rpm" % (version, arch))
                if not glob.glob(pattern):
                    missing.append("%s/%s/%s" % (distro, release, arch))
    return missing


def deb_missing(channel, version):
    missing = []
    for distro in DEBIAN_DISTROS + UBUNTU_DISTROS:
        main_dir = os.path.join(REPOS_ROOT, channel, distro, "main")
        if not os.path.isdir(main_dir):
            continue
        for arch in DEB_ARCHES:
            arch_dir = os.path.join(main_dir, "binary-%s" % arch)
            if not os.path.isdir(arch_dir):
                continue
            pattern = os.path.join(arch_dir, "xpra_%s-*_%s.deb" % (version, arch))
            if not glob.glob(pattern):
                missing.append("%s/%s" % (distro, arch))
    return missing


def macos_missing(channel, version):
    missing = []
    for arch in MACOS_ARCHES:
        arch_dir = os.path.join(REPOS_ROOT, channel, "MacOS", arch)
        if not os.path.isdir(arch_dir):
            continue
        pattern = os.path.join(arch_dir, "Xpra-%s-%s-r*.pkg" % (arch, version))
        if not glob.glob(pattern):
            missing.append("MacOS/%s" % arch)
    return missing


def mswindows_missing(channel, version):
    missing = []
    for arch in MSWINDOWS_ARCHES:
        arch_dir = os.path.join(REPOS_ROOT, channel, "MSWindows", arch)
        if not os.path.isdir(arch_dir) or os.path.islink(arch_dir):
            continue
        pattern = os.path.join(arch_dir, "Xpra-%s_%s-r*.msi" % (arch, version))
        if not glob.glob(pattern):
            missing.append("MSWindows/%s" % arch)
    return missing


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: %s <beta|stable|lts> <version>\n" % sys.argv[0])
        sys.exit(1)
    channel, version = sys.argv[1], sys.argv[2]
    channel_dir = os.path.join(REPOS_ROOT, channel)
    if not os.path.isdir(channel_dir):
        sys.stderr.write("channel directory not found: %s\n" % channel_dir)
        sys.exit(1)

    categories = [
        ("rpm", rpm_missing(channel, version)),
        ("deb", deb_missing(channel, version)),
        ("MacOS", macos_missing(channel, version)),
        ("MSWindows", mswindows_missing(channel, version)),
    ]
    total = sum(len(items) for _, items in categories)
    if total == 0:
        print("%s %s: all builds present" % (channel, version))
        return
    print("%s %s: %i missing build(s)" % (channel, version, total))
    for category, items in categories:
        if items:
            print("\n%s:" % category)
            for item in items:
                print("  %s" % item)


if __name__ == "__main__":
    main()
